altdesktop/python-dbus-next

- dbus_next/message_bus.py
- test/service/test_export.py
This patch fixes the way introspection generates node structure for requested path. 
Lets export more than one interface under similar path, eg.:
`'/test/path'` 
`'/test/path/child'` 
If a client introspects the root path '/' the response will include duplicated child node:
`<node name="/">`
`  <node name="com" />`
`    <node name="com" />`
`</node>"`
Client recursively asking and building interface tree will cause n^2 visible service interfaces where n is a number of actual service interfaces exported.
This patch fixes this behavior (test case included)
> Fix for introspection 

- dbus_next/aio/message_bus.py
- dbus_next/aio/proxy_object.py
- dbus_next/glib/message_bus.py
- dbus_next/glib/proxy_object.py
- dbus_next/introspection.py
- dbus_next/message.py
- dbus_next/message_bus.py
- dbus_next/proxy_object.py
- dbus_next/service.py
- dbus_next/signature.py
- test/service/test_export.py
- test/service/test_standard_interfaces.py
This patch adds `org.freedesktop.DBus.ObjectManager` interface to the default interfaces of the Node.
The interface implements `GetManagedObjects` method and it exposes `InterfacesAdded` and `InterfacesRemoved` although it doesn't implement automatic signal emission.
In addition this patch adds option to select the way introspection is presented. If `expanded_intr` option is True (False by default) the interface tree in introspection will be expanded i.e:
> `/` 
`/com`
`/com/example`
`/com/example/sample0`
else introspection is presented as before:
> `/com/example/sample0`
> ObjectManager interface added

- docs/index.rst
I noticed that the links in the list of core interfaces on [readthedocs](https://python-dbus-next.readthedocs.io/en/latest/index.html) are broken.
This was caused by the use of absolute paths in the link target. I changed the paths to relative ones.
> Change absolute paths to relative paths.

- dbus_next/aio/proxy_object.py
- dbus_next/glib/proxy_object.py
The current documentation on readthedocs is not showing code snippets on the pages for [aio.ProxyInterface](https://python-dbus-next.readthedocs.io/en/latest/high-level-client/aio-proxy-interface.html) and [glib.ProxyInterface](https://python-dbus-next.readthedocs.io/en/latest/high-level-client/glib-proxy-interface.html). A quick look in the [build log](https://readthedocs.org/projects/python-dbus-next/builds/10084910/) showed that for each `code-block::` the highlighting language needs to be specified.
```
/home/docs/checkouts/readthedocs.org/user_builds/python-dbus-next/checkouts/latest/dbus_next/aio/proxy_object.py:docstring of dbus_next.aio.ProxyInterface:17: WARNING: Error in "code-block" directive:
1 argument(s) required, 0 supplied.
.. code-block::
result = await …
```
> Fix code snippets on readthedocs

- test/service/test_methods.py
> Add unit tests for not sending reply when NO_REPLY_EXPECTED is set.

- dbus_next/aio/message_bus.py
- dbus_next/aio/proxy_object.py
- dbus_next/glib/message_bus.py
- dbus_next/glib/proxy_object.py
- dbus_next/introspection.py
- dbus_next/message.py
- dbus_next/message_bus.py
- dbus_next/proxy_object.py
- dbus_next/service.py
- dbus_next/signature.py
- docs/high-level-service/index.rst
- test/service/test_methods.py
> Allow coroutines in service methods

- dbus_next/message_bus.py
- dbus_next/signature.py
- test/client/test_signals.py
- test/service/test_signals.py
This patch adds functionality to send InterfacesAdded and InterfacesRemoved signal to ObjectManager.
Additional tests for signals now use reworked observer to catch messages.
> Object manager signals

- README.md
- docs/high-level-service/index.rst
- examples/example-service.py
If we first `request_name` and then `bus.export` our service
then there is a (short) period of time when we already own the name
but our MessageBus class doesn't know which services shall it provide.
As a result, if we get a request in this period of time,
we will reply with an error "SERVICE.METHOD with signature SIGNATURE not found".
This situation will happen regularly if we are started by dbus-daemon
because we were declared in the `.service` file. For example:
```
[D-BUS Service]
Name=test.name
Exec=/path/to/my/service.py
```
With the old vesion of examples, this will fail to handle the first request
for which D-Bus started our service.
> Fix race condition in examples for high level service interface

- dbus_next/message_bus.py
Also mark the translated to dbus Exceptions as handled.
> Allow to use subclasses of DBusError

- dbus_next/signature.py
It is helpful to show the received type when there is a mismatch.
Btw, running `make` will cause a lot of changes all around the codebase, so this PR is limited to only the file I edited, I hope that's fine..
> Include the received type for SignatureBodyMismatchErrors

- dbus_next/aio/proxy_object.py
- test/client/test_methods.py
Some services expose interfaces that don't send method call replies. This PR allows python-dbus-next to mark method call with NO_REPLY_EXPECTED flag.
Without this, calling such methods results in a warning in logs:
```
2020-07-10 10:28:57 root                                     ERROR     message_bus.py:573  got unexpected error processing a message: invalid state.
Traceback (most recent call last):
File "/home/khorne/Programming/silvair/python-dbus-next/dbus_next/message_bus.py", line 570, in _on_message
self._process_message(msg)
File "/home/khorne/Programming/silvair/python-dbus-next/dbus_next/message_bus.py", line 668, in _process_message
handler(msg, None)
File "/home/khorne/Programming/silvair/python-dbus-next/dbus_next/message_bus.py", line 535, in reply_notify
callback(reply, err) …
```
> Allow calling methods with no expected reply

- dbus_next/_private/unmarshaller.py
Following our discussion on discord, here is a series of patches for optimizing the `Unmarshaller` class.
To motivate these changes, here are some line profiling results. The test setup is a bit complex and I did not have time to include it with the patch. However, it involves using [line_profiler](https://github.com/pyutils/line_profiler) and subscribing to systemd units `PropertiesChanged` signals. Then, causing a lot of these signal messages to be broadcast (here, by creating a lot of virtual network devices in multiple network namespaces).
```
Timer unit: 1e-06 s
Total time: 5.26096 s
File: dbus_next/_private/unmarshaller.py
Function: read at line 42
Line #      Hits         Time  Per Hit   % Time  Line Contents
==============================================================
42 …
```
> Unmarshaller optimizations

- dbus_next/_private/unmarshaller.py
When the message header is not a multiple of 8 bytes long, there will be an additional read performed when reading the body since there is an alignment after reading the header. I forgot to take this into account in #62.
I also added a small optimization in padding computing since I needed a separate function to get header padding.
> Fix unmarshaller prefetch align

- dbus_next/message_bus.py
`socket.SOCK_NONBLOCK` does not exist on macOS, so creating a dbus instance with an unix path fails. This fix uses same socket creation as with tcp. This works on macOS 10.15.6 with dbus 1.12.20, but I don't know if it has any consequences on other platforms.
Running the tests locally with:
DBUS_SESSION_BUS_ADDRESS="unix:path=${DBUS_LAUNCHD_SESSION_BUS_SOCKET}" python3 -m pytest
Where `DBUS_LAUNCHD_SESSION_BUS_SOCKET` is something like `/private/tmp/com.apple.launchd/unix_domain_listener`.
Results in two failed tests:
```
test_signals_with_changing_owners
OSError: [Errno 57] Socket is not connected
```
```
test_tcp_connection_with_forwarding
AssertionError: assert 'abstract' in {'path': '/private/tmp/com.apple.launchd/unix_domain_listener'}
```
If I use `path` instead of `abstract` as …
> Fix socket creation on macos. SOCK_NONBLOCK does not exists.

- dbus_next/_private/constants.py
- dbus_next/_private/unmarshaller.py
- dbus_next/aio/message_bus.py
- dbus_next/aio/proxy_object.py
- dbus_next/auth.py
- dbus_next/message.py
- dbus_next/message_bus.py
- dbus_next/service.py
- test/test_fd_passing.py
Hi,
We've started working on #33. It's still very much in progress, but I wanted to give you heads up and get some feedback about the general approach.
On the other side, we'll be using https://git.kernel.org/pub/scm/libs/ell/ell.git/
> [WIP] Support passing unix fds

- dbus_next/aio/message_bus.py
This is needed to properly handle asyncio timeouts. If the future is already done, then set_exception will raise an exception and the `self.bus._finalize` call will not be reached.
I ran into this failure mode when wrapping `bus.call` in `asyncio.wait_for`:
`await asyncio.wait_for(bus.call(...), timeout=10)`
If the timeout was reached, it would cause an infinite loop of errors:
```
Traceback (most recent call last):
File "asyncio/events.py", line 127, in _run
File "site-packages/dbus_next/aio/message_bus.py", line 63, in write_callback
asyncio.base_futures.InvalidStateError: invalid state
2020-11-25 12:05:01,578 - asyncio - ERROR - Exception in callback _MessageWriter.write_callback()
handle: <Handle _MessageWriter.write_callback()>
Traceback (most recent call last):
File …
```
> Ensure future is not done when setting exception

- MANIFEST.in
py.typed needs to be included in package otherwise mypy will
throw out errors.
> Include py.typed in Manifest.in

- dbus_next/service.py
* `member` is undefined here and triggers an AttributeError, causing
user to miss the actual error message.
* Replace `member` with `prop`. Tested by creating a RW property
without a setter and got the correct error message:
```
ValueError: property "MyProp" is writable but does not have a setter
```
> Bug fix in property validation error message

- dbus_next/message_bus.py
This gets rid of unnecessary log after disconnect:
```
ERROR remove match request failed. match="type='signal',sender=org.freedesktop.DBus,interface=org.freedesktop.DBus,path=/org/freedesktop/DBus",
WARNING a message handler threw an exception on shutdown
Traceback (most recent call last):
File "/home/khorne/Programming/silvair/python-dbus-next/dbus_next/aio/message_bus.py", line 366, in _message_reader
if self._unmarshaller.unmarshall():
File "/home/khorne/Programming/silvair/python-dbus-next/dbus_next/_private/unmarshaller.py", line 304, in unmarshall
self._unmarshall()
File "/home/khorne/Programming/silvair/python-dbus-next/dbus_next/_private/unmarshaller.py", line 243, in _unmarshall
self.read(16, prefetch=True)
File "/home/khorne/Programming/silvair/python-dbus-next/dbus_next/_private …
```
> Don't log errors if call failed after disconnect

- dbus_next/validators.py
- test/test_validators.py
For gtk application(tested with Gtk-3.0), generally the registered dbus interface include snippet like this:
<interface name="org.gtk.Application">
<method name="Activate">
<arg type="a{sv}" name="platform-data" direction="in">
</arg>
</method>
Currently the member name is matched with the pattern in validators.py:
_element_re = re.compile(r'^[A-Za-z_][A-Za-z0-9_]*$')
For which name with dash like platform-data will be invalid, the pattern need to be update to support gtk application
> update the re pattern for valid name assertion

- Dockerfile
- Makefile
This fixes the travis ci builds.
python 3.6 is no longer supported[1], and is not longer supported by
get-pip.py [2]
The docker image build is improved by exiting on error inside shell for loop.
[1] https://peps.python.org/pep-0494/
[2] https://pip.pypa.io/en/stable/installation/#compatibility
> Fix make docker-test by removing python 3.6. Improve docker image build.

- dbus_next/glib/message_bus.py
See https://gitlab.gnome.org/GNOME/pygobject/-/issues/525 for an
explanation, the summary is: we need to explicitly call source.destroy()
if dispatch returns GLib.SOURCE_REMOVE.
Deleting the source by resetting it to None causes invalid memory
accesses and eventual crashes.
This can be reproduced with a basic call to
```
bus = dbus_next.glib.MessageBus(bus_type=dbus_next.BusType.SESSION).connect_sync()
```
and a `GLib.MainLoop()` after this call. Run in `valgrind --tool=memcheck`.
Fixes #113
> glib: destroy the _AuthLineSource explicitly

- docs/high-level-service/index.rst
The example from the docs on the [high-level service interface](https://python-dbus-next.readthedocs.io/en/latest/high-level-service/index.html) currently fails with: 
```python
Traceback (most recent call last):
File "example.py", line 65, in <module>
asyncio.get_event_loop().run_until_complete(main())
File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
return future.result()
File "example.py", line 61, in main
interface.changed()
AttributeError: 'ExampleInterface' object has no attribute 'changed'
```
This fixes the responsible typo.
> Fix typo in service example (docs)
